-- Seed the real catalogue.
--
-- Every item is made by hand, so prices are still being set: they are stored
-- as 0 for now (in the smallest currency unit) and will be filled in later.
-- Photos are uploaded separately into the public "products" storage bucket by
-- scripts/upload-product-images.mjs, which sets image_url per slug, so this
-- file inserts image_url as null and the upsert below never overwrites it.
--
-- Safe to run more than once: it upserts on the unique slug.

-- Clear out the original six sample products so the catalogue is only the real
-- range. These sample slugs were never ordered, so removing them is safe.
delete from public.products
where slug in (
  'soy-candle',
  'stoneware-mug',
  'wooden-bowl',
  'stoneware-planter',
  'wool-scarf',
  'tote-bag'
);

insert into public.products
  (slug, name, tagline, description, price, lot, sku, materials, dimensions, image_url, category, active)
values
  -- Crochet bouquets (custom) ------------------------------------------------
  (
    'something-blue-bouquet',
    'Something Blue Bouquet',
    'Soft blue roses that never wilt',
    'A hand-crocheted posy of powder-blue and ivory roses tucked among real dried baby''s breath. Each rose is shaped stitch by stitch, then wrapped in tissue and finished with a satin bow, so it stays in bloom long after fresh flowers would fade. Lovely for a wedding, a new baby, or anyone who loves a gentle blue.',
    0,
    '01',
    'MTC-001',
    array['Cotton yarn', 'Dried gypsophila', 'Tissue wrap', 'Satin ribbon'],
    'About 8 stems, hand-wrapped',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'single-sunflower-stem',
    'Single Sunflower Stem',
    'One little sunny hello',
    'A single crocheted sunflower with a deep chocolate centre and ruffled yellow petals, wrapped simply in burlap and tied with jute. It is the kind of small gift that brightens a desk or a bedside without ever needing water. Made one stem at a time.',
    0,
    '02',
    'MTC-002',
    array['Acrylic yarn', 'Floral wire', 'Burlap wrap', 'Jute twine'],
    '1 stem, about 35 cm tall',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'rustic-sunflower-posy',
    'Rustic Sunflower Posy',
    'Sunflowers, daisies, and a little blush',
    'A cheerful mix of crocheted sunflowers, tiny cream blossoms, and a single pink daisy, gathered in rustic burlap and tied with twine. The textures play off each other for a just-picked, farmhouse feel. Each posy is arranged by hand, so no two are exactly alike.',
    0,
    '03',
    'MTC-003',
    array['Acrylic yarn', 'Floral wire', 'Burlap wrap', 'Jute twine'],
    'Small posy, hand-arranged',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'red-rose-bouquet',
    'Red Rose Bouquet',
    'Classic red, made to last',
    'A bouquet of richly textured red roses crocheted in chunky yarn, threaded with delicate gold sprigs and wrapped in soft tissue. It carries all the romance of a dozen red roses with none of the wilting. A heartfelt pick for anniversaries and birthdays.',
    0,
    '04',
    'MTC-004',
    array['Chunky yarn', 'Dried sprigs', 'Tissue wrap', 'Jute twine'],
    'About 7 roses, hand-wrapped',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'forget-me-not-bouquet',
    'Forget-Me-Not Bouquet',
    'Little blue blooms and white tulips',
    'Clusters of tiny blue and white forget-me-nots crocheted around soft white tulips, finished in a pale blue wrap and ribbon. It is dainty and quiet, the sort of bouquet that says you were thinking of someone. Each flower is worked by hand in fine cotton.',
    0,
    '05',
    'MTC-005',
    array['Cotton yarn', 'Floral wire', 'Paper wrap', 'Satin ribbon'],
    'Mixed posy, hand-arranged',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'single-red-rose',
    'Single Red Rose',
    'One rose, all heart',
    'A single crocheted red rose on a wrapped stem, finished in soft striped paper and a twist of jute. Simple and sincere, it is made to be kept long after the moment has passed. Crocheted petal by petal for that real, full-bloom look.',
    0,
    '06',
    'MTC-006',
    array['Cotton yarn', 'Floral wire', 'Paper wrap', 'Jute twine'],
    '1 stem, hand-wrapped',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'monochrome-tulip-bouquet',
    'Monochrome Tulip Bouquet',
    'Black and white, soft to the touch',
    'A modern bunch of crocheted tulips in black and ivory, wrapped in natural burlap and tied with a white satin bow. The plump, rounded blooms feel wonderful in the hand and suit anyone who loves a more graphic, understated look. Made to order in small batches.',
    0,
    '07',
    'MTC-007',
    array['Acrylic yarn', 'Floral wire', 'Burlap wrap', 'Satin ribbon'],
    'About 5 tulips, hand-wrapped',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'garden-medley-bouquet',
    'Garden Medley Bouquet',
    'A whole garden in one bunch',
    'Our fullest bouquet: a big crocheted sunflower at the centre, ringed by roses and little blossoms in blush, cream, caramel, and blue. It is a true statement piece, arranged and wrapped by hand for birthdays and big celebrations. Every flower is individually crocheted, so it takes days to make.',
    0,
    '08',
    'MTC-008',
    array['Mixed yarn', 'Floral wire', 'Paper wrap', 'Satin ribbon'],
    'Large round bouquet',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'peach-rose-daisy-bouquet',
    'Peach Rose and Daisy Bouquet',
    'Peach roses with teal leaves',
    'Curled peach roses, white daisies, and a soft cluster bloom set against deep teal leaves and a kraft paper wrap. The warm and cool tones together feel fresh and a little unexpected. Each piece is crocheted and shaped by hand before being arranged.',
    0,
    '09',
    'MTC-009',
    array['Cotton yarn', 'Floral wire', 'Kraft wrap', 'Satin ribbon'],
    'Mixed bouquet, hand-arranged',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'rainbow-bear-bouquet',
    'Rainbow Bear Bouquet',
    'A cuddly bear on a stem',
    'A squishy pastel rainbow bear crocheted in soft chenille yarn, set on a stem and wrapped like a bouquet with little ribbon bows. It is playful and huggable, made for someone who would rather have a friend than flowers. Worked in plush velvet-soft yarn.',
    0,
    '10',
    'MTC-010',
    array['Chenille yarn', 'Polyester filling', 'Paper wrap', 'Satin ribbon'],
    'Single bear bouquet',
    null,
    'Crochet Bouquets',
    true
  ),
  (
    'blush-rose-bouquet',
    'Blush Rose Bouquet',
    'Pink and cream, with a tiny friend',
    'A soft bouquet of blush and cream crocheted roses and tulips, dotted with dried baby''s breath and a sweet little crocheted bunny peeking out. Wrapped in clean white paper, it is tender and romantic without being fussy. Made by hand from start to finish.',
    0,
    '11',
    'MTC-011',
    array['Cotton yarn', 'Dried gypsophila', 'Paper wrap', 'Satin ribbon'],
    'Mixed bouquet with plush accent',
    null,
    'Crochet Bouquets',
    true
  ),

  -- Crochet ------------------------------------------------------------------
  (
    'pouty-cat-keychain',
    'Pouty Cat Keychain',
    'Grumpy but lovable',
    'A round little cat with a pouty face and blushing cheeks, crocheted and lightly stuffed, finished with a keyring. It clips onto a bag or keys and is honestly too cute to be that grumpy. Each face is hand-stitched, so every one has its own mood.',
    0,
    '12',
    'MTC-012',
    array['Acrylic yarn', 'Polyester filling', 'Keyring'],
    'About 7 cm',
    null,
    'Crochet',
    true
  ),
  (
    'blueberry-buddy-keychain',
    'Blueberry Buddy Keychain',
    'A berry with a face',
    'A chubby navy blueberry with a tiny green leaf top and a surprised little face, crocheted and stuffed soft, on a keyring. It is the sort of small handmade charm that makes people smile when they spot it on your bag. Made one berry at a time.',
    0,
    '13',
    'MTC-013',
    array['Acrylic yarn', 'Polyester filling', 'Keyring'],
    'About 7 cm',
    null,
    'Crochet',
    true
  ),
  (
    'happy-cloud-keychain',
    'Happy Cloud Keychain',
    'A little cloud of good days',
    'A soft blue cloud with a stitched smile, hung with a hand-strung beaded charm in your colours. It is light, cheerful, and clips easily to keys or a bag. The bead strand is threaded by hand, so the little dangle is one of a kind.',
    0,
    '14',
    'MTC-014',
    array['Acrylic yarn', 'Polyester filling', 'Glass beads', 'Keyring'],
    'About 8 cm with charm',
    null,
    'Crochet',
    true
  ),
  (
    'watermelon-slice-keychain',
    'Watermelon Slice Keychain',
    'A slice of summer',
    'A juicy crocheted watermelon slice with a sleepy stitched face and tiny seed details, finished with fruit-charm sparkle and a keyring. It is bright, summery, and the right amount of silly. Made by hand in cheerful cotton.',
    0,
    '15',
    'MTC-015',
    array['Acrylic yarn', 'Polyester filling', 'Keyring'],
    'About 7 cm',
    null,
    'Crochet',
    true
  ),
  (
    'strawberry-keychain',
    'Strawberry Keychain',
    'Sweet and stitched',
    'A plump red strawberry with a leafy green crocheted top, lightly stuffed and hung from a keyring. It is a small, sweet thing to carry around and makes a lovely little gift on its own. Crocheted and shaped by hand.',
    0,
    '16',
    'MTC-016',
    array['Acrylic yarn', 'Polyester filling', 'Keyring'],
    'About 7 cm',
    null,
    'Crochet',
    true
  ),
  (
    'beaded-bow-keychain',
    'Beaded Bow Keychain',
    'A bow for your bag',
    'A chunky crocheted bow scattered with little beads, finished on a sturdy keyring and chain. It comes in a whole range of colours, from soft pink to deep red and blue, so you can pick your favourite. Each bow is crocheted and beaded by hand.',
    0,
    '17',
    'MTC-017',
    array['Acrylic yarn', 'Glass beads', 'Keyring and chain'],
    'About 9 cm wide',
    null,
    'Crochet',
    true
  ),
  (
    'flower-keychain',
    'Flower Keychain',
    'A bloom that travels with you',
    'A five-petal crocheted flower with little beaded centre dots, finished on a keyring so it can ride along on your bag or keys. Made in a range of colours to match whatever you carry. Worked by hand in soft yarn.',
    0,
    '18',
    'MTC-018',
    array['Acrylic yarn', 'Glass beads', 'Keyring'],
    'About 8 cm',
    null,
    'Crochet',
    true
  ),
  (
    'bumblebee-plushie',
    'Bumblebee Plushie',
    'A round little bee to hold',
    'A roly-poly crocheted bee in buttery yellow and black, with soft wings, safety-bead eyes, and a tiny pink bow. It sits in the palm of your hand and is made for squeezing. Stuffed soft and finished by hand.',
    0,
    '19',
    'MTC-019',
    array['Acrylic yarn', 'Polyester filling', 'Safety eyes'],
    'About 12 cm',
    null,
    'Crochet',
    true
  ),
  (
    'jute-coaster-set',
    'Jute Coaster Set',
    'Earthy mats with a pop of red',
    'A pair of round coasters crocheted in natural jute with a bright red trim that gives them a neat, finished edge. They are sturdy, washable, and bring a warm handmade touch to a coffee table. Worked in a tight spiral so they lie flat.',
    0,
    '20',
    'MTC-020',
    array['Jute twine', 'Cotton yarn'],
    'About 11 cm across, set of 2',
    null,
    'Crochet',
    true
  ),
  (
    'hand-crochet-scarf',
    'Hand-Crochet Scarf',
    'Long, warm, and yours',
    'A generously long scarf crocheted in deep navy with a soft open stitch that drapes nicely and stays cosy. It wraps easily and goes with everything, made for cold mornings and slow evenings. Each scarf takes many hours of hand work.',
    0,
    '21',
    'MTC-021',
    array['Acrylic yarn'],
    'About 180 cm long',
    null,
    'Crochet',
    true
  ),
  (
    'flower-hair-pins',
    'Flower Hair Pins',
    'Little blooms for your hair',
    'A pair of crocheted flower bobby pins, made in cheerful colours like sunny yellow, navy, and white daisy. They tuck back a fringe or dress up a half-up style with a soft handmade detail. Each tiny flower is crocheted and fixed to a slide pin by hand.',
    0,
    '22',
    'MTC-022',
    array['Cotton yarn', 'Metal bobby pins'],
    'Flower about 3 cm, set of 2',
    null,
    'Crochet',
    true
  ),
  (
    'embroidered-snap-clips',
    'Embroidered Snap Clips',
    'Soft clips, hand-embroidered',
    'Crocheted snap clips embroidered with little gardens of lavender, daisies, roses, and cherries. They hold a fringe gently and add a quiet, cottagey detail to your hair. Each clip is crocheted then embroidered stitch by stitch, so the flowers are all slightly different.',
    0,
    '23',
    'MTC-023',
    array['Cotton yarn', 'Embroidery thread', 'Metal snap clip'],
    'About 6 cm long',
    null,
    'Crochet',
    true
  ),
  (
    'little-sheep-clip',
    'Little Sheep Clip',
    'A woolly friend for Eid',
    'A soft white sheep with a black face and tiny pearl eyes, crocheted onto a clip and made with Eid ul Adha in mind. It is a sweet little keepsake for the festival or a gentle everyday hair clip. Each sheep is crocheted and finished by hand on its card.',
    0,
    '24',
    'MTC-024',
    array['Cotton yarn', 'Pearl beads', 'Metal clip'],
    'About 5 cm',
    null,
    'Crochet',
    true
  ),
  (
    'crochet-coin-purse',
    'Crochet Coin Purse',
    'A pocket-sized keeper',
    'A small round coin purse crocheted in soft buttery yellow, just right for coins, earphones, or little odds and ends. It is dense enough to hold its shape and slips easily into a bag. Worked in a snug stitch by hand.',
    0,
    '25',
    'MTC-025',
    array['Cotton yarn', 'Zip or snap closure'],
    'About 9 cm across',
    null,
    'Crochet',
    true
  ),
  (
    'potted-crochet-flower',
    'Potted Crochet Flower',
    'A bloom that needs no watering',
    'A little crocheted flower with peach petals and a cream heart, standing in its own soft green pot. It is a tiny spot of spring for a shelf or desk that stays bright all year. Crocheted and assembled entirely by hand.',
    0,
    '26',
    'MTC-026',
    array['Cotton yarn', 'Floral wire', 'Polyester filling'],
    'About 10 cm tall',
    null,
    'Crochet',
    true
  ),

  -- Candles ------------------------------------------------------------------
  (
    'honeycomb-heart-candle',
    'Honeycomb Heart Candle',
    'A heart with a honeycomb skin',
    'A plump little heart candle pressed with a fine honeycomb texture and poured in soft, pretty colours. It looks almost too good to light, but burns clean and slow when you do. Hand-poured in small batches from a smooth wax blend.',
    0,
    '27',
    'MTC-027',
    array['Soy and paraffin blend', 'Cotton wick', 'Fragrance oil'],
    'About 6 cm wide',
    null,
    'Candles',
    true
  ),
  (
    'bubble-cube-candle',
    'Bubble Cube Candle',
    'The candle that started the trend',
    'A chunky cube of soft bubbles, hand-poured in a whole rainbow of colours from blush pink to sky blue and sunny yellow. It is a playful little sculpture for a shelf and a clean, slow burn when lit. Poured by hand, so each cube is a touch unique.',
    0,
    '28',
    'MTC-028',
    array['Soy and paraffin blend', 'Cotton wick', 'Fragrance oil'],
    'About 6 cm cube',
    null,
    'Candles',
    true
  ),
  (
    'heart-cube-candle',
    'Heart Cube Candle',
    'A cube stacked with hearts',
    'A cube built from rows of little hearts, hand-poured in creamy white and soft pastels. It is romantic and modern at once, lovely as a gift or grouped with our bubble cubes. Made in small batches with a smooth, even burn.',
    0,
    '29',
    'MTC-029',
    array['Soy and paraffin blend', 'Cotton wick', 'Fragrance oil'],
    'About 6 cm cube',
    null,
    'Candles',
    true
  ),
  (
    'snowflake-candle',
    'Snowflake Candle',
    'A flurry you can keep',
    'A crisp white snowflake candle with delicate carved detail, made for winter tables and cosy gift boxes. It brings a little frost indoors and burns gently when lit. Hand-poured and turned out of its mould one at a time.',
    0,
    '30',
    'MTC-030',
    array['Soy and paraffin blend', 'Cotton wick', 'Fragrance oil'],
    'About 8 cm across',
    null,
    'Candles',
    true
  ),
  (
    'mini-jar-candle',
    'Mini Jar Candle',
    'A small light in a glass jar',
    'A little candle poured into a clear glass milk jar and tied with a wisp of organza ribbon. It is the perfect size for a bedside or a small gift, and the jar can be kept and reused after. Hand-poured with a soft scent.',
    0,
    '31',
    'MTC-031',
    array['Soy wax', 'Cotton wick', 'Glass jar', 'Organza ribbon'],
    'About 5 cm tall',
    null,
    'Candles',
    true
  ),
  (
    'seashell-candle',
    'Seashell Candle',
    'A shell washed in colour',
    'A scalloped seashell candle poured in dreamy ombre tones that fade from peach into lilac. It carries a little of the seaside and looks beautiful resting on a shelf or by a basin. Hand-poured and finished with a soft shimmer.',
    0,
    '32',
    'MTC-032',
    array['Soy and paraffin blend', 'Cotton wick', 'Mica shimmer'],
    'About 7 cm wide',
    null,
    'Candles',
    true
  ),
  (
    'daisy-flower-candle',
    'Daisy Flower Candle',
    'A bloom in soft wax',
    'A detailed daisy candle with finely layered petals, poured in gentle pinks and blush tones. It sits like a single pressed flower on a shelf and is almost too sweet to burn. Hand-poured in small batches.',
    0,
    '33',
    'MTC-033',
    array['Soy and paraffin blend', 'Cotton wick', 'Fragrance oil'],
    'About 7 cm across',
    null,
    'Candles',
    true
  ),
  (
    'rose-peony-candle',
    'Rose Peony Candle',
    'Petals layered in wax',
    'A full, rounded peony candle with soft sculpted petals, poured in dusty blues and pinks. It is a quietly elegant piece that looks lovely whether lit or simply on display. Hand-poured and hand-finished.',
    0,
    '34',
    'MTC-034',
    array['Soy and paraffin blend', 'Cotton wick', 'Fragrance oil'],
    'About 6 cm wide',
    null,
    'Candles',
    true
  ),
  (
    'coral-cluster-candle',
    'Coral Cluster Candle',
    'Like a piece of soft reef',
    'A textured candle that looks like a little cluster of coral, poured in soft pinks that fade to cream. It is a sculptural, tactile piece that brings a calm, coastal feel to a room. Hand-poured, each one slightly different.',
    0,
    '35',
    'MTC-035',
    array['Soy and paraffin blend', 'Cotton wick', 'Fragrance oil'],
    'About 7 cm tall',
    null,
    'Candles',
    true
  ),
  (
    'stacked-hearts-candle',
    'Stacked Hearts Candle',
    'A tall stack of love',
    'A tall pillar of stacked hearts, hand-poured and dotted with little raised details for a hand-finished look. It makes a striking centrepiece and a memorable gift for someone you adore. Poured and decorated by hand.',
    0,
    '36',
    'MTC-036',
    array['Soy and paraffin blend', 'Cotton wick', 'Wax dots'],
    'About 14 cm tall',
    null,
    'Candles',
    true
  ),

  -- Wooden decor -------------------------------------------------------------
  (
    'painted-honey-pot',
    'Hand-Painted Honey Pot',
    'A little village in your hand',
    'A small wooden honey pot with its own dipper, hand-painted with a tiny village scene of huts and palms. It is a charming desk or shelf piece that nods to traditional folk painting. Each pot is turned and painted by hand, so the little scenes vary.',
    0,
    '37',
    'MTC-037',
    array['Turned wood', 'Hand-painted finish', 'Lacquer'],
    'About 9 cm tall',
    null,
    'Wooden Decor',
    true
  ),
  (
    'painted-bird-pair',
    'Painted Bird Pair',
    'Two little songbirds',
    'A pair of hand-painted bird figures covered in bright folk flowers and bold colour. They perch happily on a shelf or windowsill and bring a cheerful, crafted touch to a room. Painted by hand, so each little bird is one of a kind.',
    0,
    '38',
    'MTC-038',
    array['Ceramic', 'Hand-painted finish'],
    'About 7 cm each, pair',
    null,
    'Wooden Decor',
    true
  ),
  (
    'painted-elephant-pair',
    'Painted Elephant Pair',
    'A pair for good luck',
    'Two little elephants, one in classic blue and white and one in bright folk florals, each painted entirely by hand. They make a sweet good-luck pairing for a shelf, a desk, or a thoughtful gift. No two are painted exactly alike.',
    0,
    '39',
    'MTC-039',
    array['Ceramic', 'Hand-painted finish'],
    'About 8 cm each, pair',
    null,
    'Wooden Decor',
    true
  ),
  (
    'naqshi-stacked-pots',
    'Naqshi Stacked Pots',
    'Traditional pattern, stacked tall',
    'A set of stacking pots hand-painted in deep red and black naqshi patterns, the kind of intricate work seen on traditional Multani crafts. Stacked together they make a striking decorative piece full of fine detail. Each band is painted by hand.',
    0,
    '40',
    'MTC-040',
    array['Turned wood', 'Hand-painted finish', 'Lacquer'],
    'Stacked set, about 22 cm tall',
    null,
    'Wooden Decor',
    true
  ),
  (
    'mushroom-trinket-dish',
    'Mushroom Trinket Dish',
    'A tiny dish for tiny things',
    'A little hand-painted trinket dish with a sweet toadstool and a gilded rim, just right for rings, studs, or stray pins. It is a small, useful piece of art for a dresser or desk. Shaped and painted by hand.',
    0,
    '41',
    'MTC-041',
    array['Air-dry clay', 'Hand-painted finish', 'Gold trim'],
    'About 8 cm across',
    null,
    'Wooden Decor',
    true
  ),
  (
    'calligraphy-storage-jar',
    'Calligraphy Storage Jar',
    'Blue and white, with a flourish',
    'A lidded jar hand-painted in deep cobalt with white calligraphy and fine engraved-style patterning. It is a handsome piece on its own and useful for tucking small treasures away. Painted by hand in the traditional blue and white style.',
    0,
    '42',
    'MTC-042',
    array['Ceramic', 'Hand-painted finish'],
    'About 18 cm tall',
    null,
    'Wooden Decor',
    true
  ),

  -- Gift baskets -------------------------------------------------------------
  (
    'soft-girl-beauty-crate',
    'Soft Girl Beauty Crate',
    'A plush and a little glam',
    'A wooden crate tied with pink bows and packed with a soft cat plush, a perfume, lip and cheek colour, and a cute character gloss set. It is a ready-to-give bundle for a birthday or a treat-yourself moment. Each crate is styled and tied by hand.',
    0,
    '43',
    'MTC-043',
    array['Wooden crate', 'Assorted gifts', 'Satin bows'],
    'One styled crate',
    null,
    'Gift Baskets',
    true
  ),
  (
    'with-love-gift-box',
    'With Love Gift Box',
    'A box of little handmade things',
    'A soft little box bringing together our crocheted keychains and a few hand-poured candles, packed in tissue with a handwritten note. It is a gentle, thoughtful gift that feels personal from the moment it is opened. Put together by hand, and easy to make your own.',
    0,
    '44',
    'MTC-044',
    array['Crochet charms', 'Hand-poured candles', 'Gift box', 'Handwritten note'],
    'One curated box',
    null,
    'Gift Baskets',
    true
  ),
  (
    'favourite-person-memory-box',
    'Favourite Person Memory Box',
    'Photos, treats, and a lantern glow',
    'A keepsake box lined with a collage of your photos and filled with little things they love: bangles, a mirror, glitter, sweets, and a glowing lantern. It is made for the person you would call your favourite, and every box is personalised. Styled and assembled by hand.',
    0,
    '45',
    'MTC-045',
    array['Keepsake box', 'Printed photos', 'Assorted gifts', 'Lantern'],
    'One personalised box',
    null,
    'Gift Baskets',
    true
  ),
  (
    'chocolate-lovers-hamper',
    'Chocolate Lover''s Hamper',
    'For a serious sweet tooth',
    'A clear-fronted basket piled with chocolates and treats, from Cadbury and Kinder Bueno to Raffaello and Mars, tied with deep red ribbon. It is a generous, crowd-pleasing gift for birthdays and celebrations. Arranged and wrapped by hand.',
    0,
    '46',
    'MTC-046',
    array['Gift basket', 'Assorted chocolates', 'Satin ribbon', 'Cellophane wrap'],
    'One filled basket',
    null,
    'Gift Baskets',
    true
  ),
  (
    'eid-mubarak-hamper',
    'Eid Mubarak Hamper',
    'A warm Eid greeting',
    'A festive hamper wrapped in organza and cellophane with red bows and an Eid Mubarak tag, filled with sweets and little treats. It is a lovely way to send the warmth of the festival to family and friends. Each hamper is styled and tied by hand.',
    0,
    '47',
    'MTC-047',
    array['Gift basket', 'Assorted treats', 'Organza wrap', 'Satin bows'],
    'One festive hamper',
    null,
    'Gift Baskets',
    true
  ),
  (
    'mehndi-festivity-basket',
    'Mehndi Festivity Basket',
    'Dressed up for the celebration',
    'A golden tray basket styled for mehndi and wedding festivities, with bangles, earrings, mehndi cone, chocolates, and a crocheted sunflower scrunchie tucked in. It is celebratory and full of little details, ready to gift or display. Arranged by hand for the occasion.',
    0,
    '48',
    'MTC-048',
    array['Gold tray basket', 'Bangles and jewellery', 'Assorted treats', 'Crochet accent'],
    'One styled basket',
    null,
    'Gift Baskets',
    true
  ),
  (
    'birthday-snack-hamper',
    'Birthday Snack Hamper',
    'Snacks, sweets, and a bouquet',
    'A birthday basket loaded with favourite snacks and chocolates, from Lays and Cheetos to Buldak and Dairy Milk, styled with balloons and a red and white rose bunch. It is a fun, festive bundle that lands the celebration straight away. Styled and wrapped by hand.',
    0,
    '49',
    'MTC-049',
    array['Gift basket', 'Assorted snacks', 'Rose bunch', 'Tulle wrap'],
    'One filled basket',
    null,
    'Gift Baskets',
    true
  )
on conflict (slug) do update set
  name        = excluded.name,
  tagline     = excluded.tagline,
  description = excluded.description,
  price       = excluded.price,
  lot         = excluded.lot,
  sku         = excluded.sku,
  materials   = excluded.materials,
  dimensions  = excluded.dimensions,
  category    = excluded.category,
  active      = excluded.active;
  -- image_url is intentionally left out of the update so re-running this seed
  -- never wipes photos already uploaded by scripts/upload-product-images.mjs.
